In [140]:
import pandas as pd
import numpy as np
import pymongo
import matplotlib.pyplot as plt
import math

In [11]:
client = pymongo.MongoClient("mongodb+srv://root:root@cluster10.odazv.mongodb.net/?retryWrites=true&w=majority")
db = client.test

In [12]:
data = pd.read_csv('Datasets/SkewOutliersMulticorr')
data.head()

Temperature  RH  Ws  Rain     FFMC  DMC    DC  ISI  FWI  Classes
0         29.0  57  18  0.00  65.7000  3.4   7.6  1.3  0.5        0
1         29.0  61  13  1.25  64.4000  4.1   7.6  1.0  0.4        0
2         26.0  82  22  1.25  47.7375  2.5   7.1  0.3  0.1        0
3         25.0  89  13  1.25  47.7375  1.3   6.9  0.0  0.0        0
4         27.0  77  16  0.00  64.8000  3.0  14.2  1.2  0.5        0

In [13]:
new_data = data.iloc[60:120, :8]

In [14]:
new_data.shape

(60, 8)

In [15]:
batch_data = new_data.to_dict(orient='records')
batch_data

[{'Temperature': 35.0,
  'RH': 64,
  'Ws': 17,
  'Rain': 0.0,
  'FFMC': 87.2,
  'DMC': 31.9,
  'DC': 145.7,
  'ISI': 6.8},
 {'Temperature': 36.0,
  'RH': 45,
  'Ws': 14,
  'Rain': 0.0,
  'FFMC': 78.8,
  'DMC': 4.8,
  'DC': 10.2,
  'ISI': 2.0},
 {'Temperature': 35.0,
  'RH': 55,
  'Ws': 12,
  'Rain': 0.4,
  'FFMC': 78.0,
  'DMC': 5.8,
  'DC': 10.0,
  'ISI': 1.7},
 {'Temperature': 35.0,
  'RH': 63,
  'Ws': 14,
  'Rain': 0.3,
  'FFMC': 76.6,
  'DMC': 5.7,
  'DC': 10.0,
  'ISI': 1.7},
 {'Temperature': 34.0,
  'RH': 69,
  'Ws': 13,
  'Rain': 0.0,
  'FFMC': 85.0,
  'DMC': 8.2,
  'DC': 19.8,
  'ISI': 4.0},
 {'Temperature': 34.0,
  'RH': 65,
  'Ws': 13,
  'Rain': 0.0,
  'FFMC': 86.8,
  'DMC': 11.1,
  'DC': 29.7,
  'ISI': 5.2},
 {'Temperature': 32.0,
  'RH': 75,
  'Ws': 14,
  'Rain': 0.0,
  'FFMC': 86.4,
  'DMC': 13.0,
  'DC': 39.1,
  'ISI': 5.2},
 {'Temperature': 32.0,
  'RH': 69,
  'Ws': 16,
  'Rain': 0.0,
  'FFMC': 86.5,
  'DMC': 15.5,
  'DC': 48.6,
  'ISI': 5.5},
 {'Temperature': 32.0,
  'R

### Connecting...

In [16]:
db = client['Algerian_Forest-Fires']

In [17]:
collection = db['Forest-Fires']

In [18]:
# collection.insert_many(batch_data)

In [227]:
list_cursor = list(collection.find())

In [224]:
ls = []
for i in list_cursor:
    del i['_id']
    ls.append(i)

In [228]:
ls

[{'Temperature': 35,
  'RH': 64,
  'Ws': 17,
  'Rain': 0.0,
  'FFMC': 87.2,
  'DMC': 31.9,
  'DC': 145.7,
  'ISI': 6.8},
 {'Temperature': 36,
  'RH': 45,
  'Ws': 14,
  'Rain': 0.0,
  'FFMC': 78.8,
  'DMC': 4.8,
  'DC': 10.2,
  'ISI': 2.0},
 {'Temperature': 35,
  'RH': 55,
  'Ws': 12,
  'Rain': 0.4,
  'FFMC': 78.0,
  'DMC': 5.8,
  'DC': 10.0,
  'ISI': 1.7},
 {'Temperature': 35,
  'RH': 63,
  'Ws': 14,
  'Rain': 0.3,
  'FFMC': 76.6,
  'DMC': 5.7,
  'DC': 10.0,
  'ISI': 1.7},
 {'Temperature': 34,
  'RH': 69,
  'Ws': 13,
  'Rain': 0.0,
  'FFMC': 85.0,
  'DMC': 8.2,
  'DC': 19.8,
  'ISI': 4.0},
 {'Temperature': 34,
  'RH': 65,
  'Ws': 13,
  'Rain': 0.0,
  'FFMC': 86.8,
  'DMC': 11.1,
  'DC': 29.7,
  'ISI': 5.2},
 {'Temperature': 32,
  'RH': 75,
  'Ws': 14,
  'Rain': 0.0,
  'FFMC': 86.4,
  'DMC': 13.0,
  'DC': 39.1,
  'ISI': 5.2},
 {'Temperature': 32,
  'RH': 69,
  'Ws': 16,
  'Rain': 0.0,
  'FFMC': 86.5,
  'DMC': 15.5,
  'DC': 48.6,
  'ISI': 5.5},
 {'Temperature': 32,
  'RH': 60,
  'Ws': 18

#### Deployment Purpose:

In [186]:
# pd.DataFrame(list_cursor)

test_data = pd.DataFrame(ls[:200], index=None)

In [187]:
test_data.head()
# test_data.shape

Temperature  RH  Ws  Rain  FFMC   DMC     DC  ISI
0         35.0  64  17   0.0  87.2  31.9  145.7  6.8
1         36.0  45  14   0.0  78.8   4.8   10.2  2.0
2         35.0  55  12   0.4  78.0   5.8   10.0  1.7
3         35.0  63  14   0.3  76.6   5.7   10.0  1.7
4         34.0  69  13   0.0  85.0   8.2   19.8  4.0

In [162]:
import pickle
reg = pickle.load(open('Regression.pkl', 'rb'))
clas = pickle.load(open('Classification.pkl', 'rb'))
scale = pickle.load(open('Features_Scaled.pkl', 'rb'))

In [113]:
scaled_data = scale.transform(test_data)

In [114]:
output = clas.predict(scaled_data)
output

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 1], dtype=int64)

In [115]:
test_data['PREDICTED'] = output

In [116]:
# test_data.to_html("templates/batch_class.html")

In [117]:
myhtml = test_data.style.set_properties(**{'font-size':'14pt', 'font-family':'Calibri', 'border-collapse':'collapse',
                                           'background-color':'black', 'color':'lawngreen','border': '2px solid brown', 
                                           'padding': '10px','border-bottom-left-radius': '25px'}).render()

In [118]:
with open("templates/batch_class.html", "wb") as f:
    tags = myhtml.encode('utf-8')
    f.write(tags)

In [100]:
type(myhtml)

str

### Testing:

In [39]:
import pickle

In [40]:
reg = pickle.load(open('Regression.pkl', 'rb'))
clas = pickle.load(open('Classification.pkl', 'rb'))
scale = pickle.load(open('Features_Scaled.pkl', 'rb'))

In [ ]:
series = test_data.to_numpy()
values = np.array(list(series)).reshape(len(series), -1)
values

In [41]:
# Array values:
values = scale.transform(values)

In [42]:
clas.predict(values)

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 1], dtype=int64)

In [43]:
# DataFrame values:
test_data = scale.transform(test_data)

In [44]:
clas.predict(test_data)

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 1], dtype=int64)

### Getting Randomized datas from database:

In [214]:
data = test_data.copy()

In [222]:
ls

[{'Temperature': 35,
  'RH': 64,
  'Ws': 17,
  'Rain': 0.0,
  'FFMC': 87.2,
  'DMC': 31.9,
  'DC': 145.7,
  'ISI': 6.8},
 {'Temperature': 36,
  'RH': 45,
  'Ws': 14,
  'Rain': 0.0,
  'FFMC': 78.8,
  'DMC': 4.8,
  'DC': 10.2,
  'ISI': 2.0},
 {'Temperature': 35,
  'RH': 55,
  'Ws': 12,
  'Rain': 0.4,
  'FFMC': 78.0,
  'DMC': 5.8,
  'DC': 10.0,
  'ISI': 1.7},
 {'Temperature': 35,
  'RH': 63,
  'Ws': 14,
  'Rain': 0.3,
  'FFMC': 76.6,
  'DMC': 5.7,
  'DC': 10.0,
  'ISI': 1.7},
 {'Temperature': 34,
  'RH': 69,
  'Ws': 13,
  'Rain': 0.0,
  'FFMC': 85.0,
  'DMC': 8.2,
  'DC': 19.8,
  'ISI': 4.0},
 {'Temperature': 34,
  'RH': 65,
  'Ws': 13,
  'Rain': 0.0,
  'FFMC': 86.8,
  'DMC': 11.1,
  'DC': 29.7,
  'ISI': 5.2},
 {'Temperature': 32,
  'RH': 75,
  'Ws': 14,
  'Rain': 0.0,
  'FFMC': 86.4,
  'DMC': 13.0,
  'DC': 39.1,
  'ISI': 5.2},
 {'Temperature': 32,
  'RH': 69,
  'Ws': 16,
  'Rain': 0.0,
  'FFMC': 86.5,
  'DMC': 15.5,
  'DC': 48.6,
  'ISI': 5.5},
 {'Temperature': 32,
  'RH': 60,
  'Ws': 18

In [11]:
input_value=20

In [14]:
import numpy as np
import math 

start = np.random.randint(240)
end = np.random.randint(240)
print(start, end)

77 214


In [15]:
rand = np.linspace(start,end, input_value)
rand

array([ 77.        ,  77.68844221,  78.37688442,  79.06532663,
        79.75376884,  80.44221106,  81.13065327,  81.81909548,
        82.50753769,  83.1959799 ,  83.88442211,  84.57286432,
        85.26130653,  85.94974874,  86.63819095,  87.32663317,
        88.01507538,  88.70351759,  89.3919598 ,  90.08040201,
        90.76884422,  91.45728643,  92.14572864,  92.83417085,
        93.52261307,  94.21105528,  94.89949749,  95.5879397 ,
        96.27638191,  96.96482412,  97.65326633,  98.34170854,
        99.03015075,  99.71859296, 100.40703518, 101.09547739,
       101.7839196 , 102.47236181, 103.16080402, 103.84924623,
       104.53768844, 105.22613065, 105.91457286, 106.60301508,
       107.29145729, 107.9798995 , 108.66834171, 109.35678392,
       110.04522613, 110.73366834, 111.42211055, 112.11055276,
       112.79899497, 113.48743719, 114.1758794 , 114.86432161,
       115.55276382, 116.24120603, 116.92964824, 117.61809045,
       118.30653266, 118.99497487, 119.68341709, 120.37

In [219]:
import math
floor = []
for i in rand:
    floor.append(math.floor(i))

print(floor)

[167, 149, 132, 115, 98, 81]


In [220]:
arr = []
for i in floor:
    arr.append(ls[i])
print(arr)

[{'Temperature': 30, 'RH': 65, 'Ws': 14, 'Rain': 0.0, 'FFMC': 78.1, 'DMC': 3.2, 'DC': 15.7, 'ISI': 1.9}, {'Temperature': 35, 'RH': 48, 'Ws': 18, 'Rain': 0.0, 'FFMC': 90.1, 'DMC': 43.175, 'DC': 150.46250000000003, 'ISI': 12.5}, {'Temperature': 35, 'RH': 51, 'Ws': 13, 'Rain': 0.3, 'FFMC': 81.3, 'DMC': 15.6, 'DC': 75.1, 'ISI': 2.5}, {'Temperature': 29, 'RH': 65, 'Ws': 19, 'Rain': 0.6, 'FFMC': 68.3, 'DMC': 5.5, 'DC': 15.2, 'ISI': 1.5}, {'Temperature': 31, 'RH': 71, 'Ws': 17, 'Rain': 0.3, 'FFMC': 69.6, 'DMC': 3.2, 'DC': 30.1, 'ISI': 1.5}, {'Temperature': 36, 'RH': 58, 'Ws': 19, 'Rain': 0.0, 'FFMC': 88.6, 'DMC': 29.6, 'DC': 141.1, 'ISI': 9.2}]


In [221]:
df = pd.DataFrame(arr)
df

Temperature  RH  Ws  Rain  FFMC     DMC        DC   ISI
0           30  65  14   0.0  78.1   3.200   15.7000   1.9
1           35  48  18   0.0  90.1  43.175  150.4625  12.5
2           35  51  13   0.3  81.3  15.600   75.1000   2.5
3           29  65  19   0.6  68.3   5.500   15.2000   1.5
4           31  71  17   0.3  69.6   3.200   30.1000   1.5
5           36  58  19   0.0  88.6  29.600  141.1000   9.2

In [208]:
data[data.index==199]

Temperature  RH  Ws  Rain  FFMC   DMC     DC  ISI
199         35.0  62  19   0.0  89.4  23.2  120.9  9.7

In [1]:
ls =[2]

In [3]:
ls[0]


2